networks:
  myNetwork:
    name: myNetwork
    driver: bridge

services:
#  producer:
#    build: ./cmd/producer
#    hostname: producer
#    networks:
#      - myNetwork
#    ports:
#      - "7700:7700"
#  consumer:
#    build: ./cmd/consumer
#    networks:
#      - myNetwork
#    hostname: consumer
#    links:
#      - kafka:kafka
  zookeeper:
    restart: always
    container_name: kafka-like-zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: apache/kafka:latest
    networks:
      - myNetwork
    ports:
      - '9092:9092'
    environment:
      SERVICES_ZOOKEEPER: "zookeeper:2181"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'