# syntax=docker/dockerfile:1
FROM golang:1.23-alpine

# RUN apt-get -y update && apt-get install gcc g++
RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev librdkafka-dev pkgconf

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
COPY *.go .
# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy

RUN go mod tidy
RUN go mod download

# Build
RUN CGO_ENABLED=1 GOOS=linux go build -tags dynamic -o bin/app

# Run
CMD ["bin/app"]
