# syntax=docker/dockerfile:1
FROM golang:1.23-alpine

# RUN apt-get -y update && apt-get install gcc g++
RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev librdkafka-dev pkgconf

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
COPY *.go .
# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy

RUN mkdir bin

RUN go mod tidy
RUN go mod download

# Build
RUN CGO_ENABLED=1 GOOS=linux go build -tags dynamic -o bin/app

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 9090

# Run
CMD ["bin/app"]
